### ISSUE TITLE
Do we have access to push to this repo?

### ISSUE THREAD

**Issue by BookOwl** [SilversApprentice/-ATC-X-Veni-Vidi-Vici#3]
If so, what's stopping me from NUKING EVERYTHING!!!

In this repo, that is. Not the planet 📦

**Comment by BookOwl** [comment]
Maybe each team should just have their own fork and we submit our work with pull requests.

**Comment by bwbw223** [comment]
Um git is a version control system...  It can be rolled back

**Comment by BookOwl** [comment]
Yes, but it would be annoying to do that.

**Comment by bwbw223** [comment]
I guess...  But I *hope* we're all trustworthy enough...

**Comment by BookOwl** [comment]
Tell that to @nanalan.

**Comment by bwbw223** [comment]
?

**Comment by SilversApprentice** [comment]
@BookOwl Morality

**Comment by BookOwl** [comment]
He's always joking about nuking repos.

**Comment by SilversApprentice** [comment]
Theoretically, you could nuke it, but I would just roll it back.

**Comment by bwbw223** [comment]
I think you can delete old commits with git too though

**Comment by SilversApprentice** [comment]
@bwbw223 I'm of the opinion that if you have a need to cheat and delete things, or feel a need to delete stuff maliciously, then you shouldn't even be doing the ATC's

**Comment by TheUltimatum** [comment]
Hoi.

**Comment by SilversApprentice** [comment]
Anyway, the answer is yes, you do, and anyone that nukes the repo will be disqualified
