### ISSUE TITLE
You can't decrypt the "encryption"

### ISSUE THREAD

**Issue by BookOwl** [SilversApprentice/-ATC-X-Veni-Vidi-Vici#4]
`encryption1` uses random numbers in the encryption, with no way to influence which random numbers get picked. This makes it impossible to decrypt.

**Comment by bwbw223** [comment]
Brute force?

**Comment by bwbw223** [comment]
I don't think it is crypto random though, so it will lean toward certain numbers...

**Comment by joker314** [comment]
Well, you cannot know from the password and ciphertext what the input was.

**Comment by bwbw223** [comment]
yes

**Comment by SilversApprentice** [comment]
`encrypt1` would have to be brute-forced, and note that I'm scoring points per encryption broken, you don't have to break them all

**Comment by BookOwl** [comment]
You can't brute force it because the different strings can "encrypt" to the same text, thus you can't tell which string it should decrypt to.

**Comment by SilversApprentice** [comment]
hmm... I guess you have a point

**Comment by bwbw223** [comment]
lol maybe you should make your own solution first to make sure it's possible

**Comment by SilversApprentice** [comment]
There I just removed the `encrypt1` function :P

**Comment by TheUltimatum** [comment]
:|

**Comment by BookOwl** [comment]
No you didn't...

**Comment by TheUltimatum** [comment]
@BookOwl Is correct.

**Comment by SilversApprentice** [comment]
@BookOwl Actually I did, then I renamed `encrypt2` to `encrypt1` and added in my `encrypt3`, which I renamed to `encrypt1`

**Comment by BookOwl** [comment]
I still don't think that you can decrypt it, because it relies on random numbers that are not influenced by the password.

**Comment by joker314** [comment]
Try running the program twice on the same input. If it produces the same output - it is possible to decode, and if not, then I agree with you @BookOwl

**Comment by TheUltimatum** [comment]
@joker314 It changes every time. But it may be possible to use probability to raise the chances of proper decryption...

**Comment by SilversApprentice** [comment]
@TheUltimatum I don't think you are using the right program, then. [This](https://repl.it/E6ad) is an exact copy of the program, other than that section at the end. As you can see, it gives the same result 1000 times over

**Comment by joker314** [comment]
Ah yes, with the updated code, which does not contain a psedorandom number instruction, it is solveable.

**Comment by TheUltimatum** [comment]
... The code still contains Math.random()

**Comment by TheUltimatum** [comment]
Is it just not updating for me?

**Comment by joker314** [comment]
Hmm, what line?

Try shift clicking the reload button when reloading the code page

**Comment by TheUltimatum** [comment]
Line 30.

**Comment by BookOwl** [comment]
I figured it out. The random number is used on line 30 like so: `Math.random() * encryptHelp`
Hm, what's `encryptHelp`?
`var encryptHelp = 0;`
So no matter what Math.random() returns, the result is always 0

**Comment by TheUltimatum** [comment]
Ah...

**Comment by SilversApprentice** [comment]
Well, if that's all, I do believe I'll close this now.
